import type { Patient } from "./patients";

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "a1000001-0000-4000-8000-000000000001",
    fullName: "Alina Bianca",
    phone: "+373 60 000 000",
    birthDate: "1989-04-15",
    address: "Balti, Stefan Cel Mare, 13",
    idnp: "33333333333333",
    lastVisitDate: "2026-07-28",
    complaints:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad at autem beata debitis, distinctio dolore explicabo harum illum, ipsa molestiae nam pariatur porro, quibusdam quidem quod quos repudiandae! Delectus?",
    anamnesis:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid, architecto aut consectetur culpa dolorem dolores doloribus eaque enim, expedita facere fugit impedit ipsam laboriosam nemo officiis quia repellat, repellendus sed totam!",
    objectiveExam:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid, architecto aut consectetur culpa dolorem dolores doloribus eaque enim, expedita facere fugit impedit ipsam laboriosam nemo officiis quia repellat, repellendus sed totam!",
    diagnosis:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut cumque incidunt molestias nisi nobis perferendis quae repellendus sed tempora veniam?",
    investigations:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci dicta ipsa maxime quod saepe tempora ullam. Aliquid aperiam assumenda atque commodi debitis dolores expedita, hic ipsum, molestias nisi tempore vitae.",
    recommendations:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aspernatur doloremque ea earum eius, esse, eveniet ex fugit incidunt nulla perferendis quisquam recusandae reprehenderit rerum saepe sapiente soluta tempora veritatis voluptate voluptatum?",
    treatment:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aspernatur doloremque ea earum eius, esse, eveniet ex fugit incidunt nulla perferendis quisquam recusandae reprehenderit rerum saepe sapiente soluta tempora veritatis voluptate voluptatum?",
    procedure: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    product:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aliquid eum fugiat. Aspernatur aut, cumque excepturi facilis fuga fugit, labore laboriosam laborum maiores minima natus obcaecati odio officiis perferendis placeat provident quasi qui quia, quisquam quos repellendus rerum suscipit vitae.",
    patientConsent: true,
  },
  {
    id: "a1000001-0000-4000-8000-000000000002",
    fullName: "Ion Popescu |test",
    phone: "+373 69123456",
    birthDate: "1985-03-22",
    address: "Chișinău, str. Ștefan cel Mare 120",
    idnp: "1850322145678",
    lastVisitDate: "2026-07-25",
    complaints: "Erupții cutanate pe față, mâncărime ușoară.",
    anamnesis: "Alergie la polen. Fără boli cronice cunoscute.",
    objectiveExam: "Eritem ușor pe obraji, fără leziuni purulente.",
    diagnosis: "Dermatită seboreică ușoară.",
    investigations: "Examen dermatoscopic — fără anomalii.",
    recommendations: "Evitarea produselor agresive, SPF 50 zilnic.",
    treatment: "Cremă calmantă de 2 ori pe zi, 14 zile.",
    procedure: "Consult dermatologic",
    product: "Cremă hidratantă cu niacinamidă",
    patientConsent: true,
  },
  {
    id: "a1000001-0000-4000-8000-000000000003",
    fullName: "Maria Rusu |test",
    phone: "+373 78901234",
    birthDate: "1992-11-08",
    address: "Bălți, str. Independenței 45",
    idnp: "2921108123456",
    lastVisitDate: "2026-07-20",
    complaints: "Pigmentare post-acnee pe frunte.",
    anamnesis: "Acnee juvenilă în anii anteriori, tratată local.",
    objectiveExam: "Macule hiperpigmentare postinflamatorii, 3-5 mm.",
    diagnosis: "Postinflammatory hyperpigmentation.",
    investigations: "",
    recommendations: "Protecție solară, evitarea expunerii prelungite.",
    treatment: "Ser cu vitamina C dimineața.",
    procedure: "Peeling superficial",
    product: "Ser vitamina C 15%",
    patientConsent: true,
  },
  {
    id: "a1000001-0000-4000-8000-000000000004",
    fullName: "Elena Ciobanu |test",
    phone: "+373 60111222",
    birthDate: "1978-06-14",
    address: "Cahul, str. Republicii 7",
    idnp: "1780614234567",
    lastVisitDate: "2026-07-15",
    complaints: "Riduri fine perioculare.",
    anamnesis: "Fumătoare ocazională, fototip III.",
    objectiveExam: "Riduri dinamice moderate, elasticitate redusă ușor.",
    diagnosis: "Photoaging grade I-II.",
    investigations: "Analiză visioface — deshidratare ușoară.",
    recommendations: "Renunțare la fumat, hidratare intensivă.",
    treatment: "Botox periocular — planificat.",
    procedure: "Consult anti-aging",
    product: "Cremă retinol 0.3%",
    patientConsent: false,
  },
  {
    id: "a1000001-0000-4000-8000-000000000005",
    fullName: "Dmitri Cojocari |test",
    phone: "+373 69222333",
    birthDate: "1995-01-30",
    address: "Chișinău, bd. Dacia 88",
    idnp: "1950130987654",
    lastVisitDate: "2026-07-10",
    complaints: "Acnee vulgară pe barbie și frunte.",
    anamnesis: "Antecedente familiale de acnee.",
    objectiveExam: "Comedoni deschiși și închiși, papule inflamatorii ușoare.",
    diagnosis: "Acnee vulgară grad I.",
    investigations: "",
    recommendations: "Curățare blândă de 2 ori pe zi.",
    treatment: "Gel cu peroxid de benzoil 5%, seara.",
    procedure: "Curățare profesională",
    product: "Gel BP 5%",
    patientConsent: true,
  },
  {
    id: "a1000001-0000-4000-8000-000000000006",
    fullName: "Ana Munteanu |test",
    phone: "+373 78333444",
    birthDate: "2000-09-05",
    address: "Orhei, str. Vasile Lupu 22",
    idnp: "2000905123456",
    lastVisitDate: "2026-07-05",
    complaints: "",
    anamnesis: "",
    objectiveExam: "",
    diagnosis: "",
    investigations: "",
    recommendations: "",
    treatment: "",
    procedure: "",
    product: "",
    patientConsent: false,
  },
  {
    id: "a1000001-0000-4000-8000-000000000007",
    fullName: "Viorica Rotari |test",
    phone: "+373 60444555",
    birthDate: "1965-12-19",
    address: "Chișinău, str. Armenească 33",
    idnp: "1651219123456",
    lastVisitDate: "2026-06-28",
    complaints: "Pete senile pe mâini și decolteu.",
    anamnesis: "Hipertensiune controlată medicamentos.",
    objectiveExam: "Lentigo solare multiple, fără semne de malignitate.",
    diagnosis: "Lentigo solaris.",
    investigations: "Dermatoskopie — benign.",
    recommendations: "SPF 50, examen anual.",
    treatment: "Laser Q-switched — 2 ședințe planificate.",
    procedure: "Laser terapie",
    product: "Protecție solară minerală",
    patientConsent: true,
  },
  {
    id: "a1000001-0000-4000-8000-000000000008",
    fullName: "Andrei Botnari |test",
    phone: "+373 69555666",
    birthDate: "1988-07-03",
    address: "Ungheni, str. Națională 11",
    idnp: "1880703234567",
    lastVisitDate: "2026-06-20",
    complaints: "Cădere accentuată a părului.",
    anamnesis: "Stres profesional recent, fără alte boli.",
    objectiveExam: "Rarefacție difuză, fără cicatrici.",
    diagnosis: "Alopecie telogenă.",
    investigations: "Trichoscopie — faza telogenă crescută.",
    recommendations: "Reducerea stresului, alimentație echilibrată.",
    treatment: "Minoxidil 5% topic, 6 luni.",
    procedure: "Consult trichologic",
    product: "Minoxidil 5% soluție",
    patientConsent: true,
  },
  {
    id: "a1000001-0000-4000-8000-000000000009",
    fullName: "Natalia Gheorghe |test",
    phone: "+373 78666777",
    birthDate: "1998-04-27",
    address: "Chișinău, str. Alba Iulia 56",
    idnp: "1980427123456",
    lastVisitDate: "2026-06-15",
    complaints: "Rosacee — roșeață facială persistentă.",
    anamnesis: "Sensibilitate la alcool și condimente.",
    objectiveExam: "Eritem centrofacial, telangiectazii fine.",
    diagnosis: "Rosacee tip I (eritemato-telangiectatic).",
    investigations: "",
    recommendations: "Evitarea factorilor declanșatori, SPF zilnic.",
    treatment: "Metronidazol gel 1%, dimineața și seara.",
    procedure: "Consult rosacee",
    product: "Metronidazol gel 1%",
    patientConsent: true,
  },
  {
    id: "a1000001-0000-4000-8000-000000000010",
    fullName: "Olga Cazacu |test",
    phone: "+373 60777888",
    birthDate: "1972-02-11",
    address: "Comrat, str. Lenin 9",
    idnp: "1720211123456",
    lastVisitDate: "2026-06-01",
    complaints: "Verucă plantară dreaptă.",
    anamnesis: "Contact frecvent cu piscina publică.",
    objectiveExam: "Leziune keratotică 8 mm pe talpa dreaptă.",
    diagnosis: "Verruca vulgaris plantaris.",
    investigations: "",
    recommendations: "Evitarea mersului desculț în zone comune.",
    treatment: "Crioterapie — 3 ședințe la 2 săptămâni.",
    procedure: "Crioterapie",
    product: "",
    patientConsent: true,
  },
  {
    id: "a1000001-0000-4000-8000-000000000011",
    fullName: "Victor Sîrbu |test",
    phone: "+373 69888999",
    birthDate: "1990-10-16",
    address: "Chișinău, str. Ismail 102",
    idnp: "1901016123456",
    lastVisitDate: "2026-05-22",
    complaints: "Usturime după bărbierit.",
    anamnesis: "Piele sensibilă, fără alergii medicamentoase.",
    objectiveExam: "Foliculită post-barba ușoară pe gât.",
    diagnosis: "Pseudofolliculitis barbae.",
    investigations: "",
    recommendations: "Bărbierit cu lamă unică, sensul firelor.",
    treatment: "Loțiune after-shave fără alcool.",
    procedure: "Consult",
    product: "After-shave calmant",
    patientConsent: false,
  },
  {
    id: "a1000001-0000-4000-8000-000000000012",
    fullName: "Irina Lungu |test",
    phone: "+373 78000111",
    birthDate: "1983-08-25",
    address: "Edineț, str. Independenței 3",
    idnp: "1830825123456",
    lastVisitDate: "2026-05-10",
    complaints: "Pete pigmentare extinse după sarcină.",
    anamnesis: "Melasma post-partum, alăptează încă.",
    objectiveExam: "Macule brune simetrice pe frunte și mustață.",
    diagnosis: "Melasma.",
    investigations: "Wood lamp — epidermal predominant.",
    recommendations:
      "Protecție solară strictă. Evitarea procedurilor agresive în perioada alăptării. Reevaluare la 3 luni. Monitorizare lunară a pigmentării. Aplicare uniformă a filtrelor solare mineral și chimic combinat. Limitarea expunerii UV între orele 10-16. Utilizarea pălăriei cu boruri largi. Hidratare corespunzătoare a barierei cutanate. Evitarea produselor cu hidrochinonă în perioada alăptării. Consult de follow-up obligatoriu.",
    treatment: "Azelaic acid 15% — aplicare seara.",
    procedure: "Consult melasmă",
    product: "Azelaic acid 15% cream",
    patientConsent: true,
  },
];
